### ISSUE TITLE
get_transactions, Failed to parse server response

### ISSUE THREAD

**Issue by lorepieri8** [bonustrack/libra-grpc#12]
### Expected behavior

Error free log.

### Actual behavior

`Promise { <pending> }
> Error: 13 INTERNAL: Failed to parse server response
    at Object.exports.createStatusError (/Users/lorenzo/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/lorenzo/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/Users/lorenzo/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/lorenzo/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/lorenzo/node_modules/grpc/src/client_interceptors.js:845:24) {
  code: 13,
  metadata: undefined,
  details: 'Failed to parse server response'
} null`

### Steps to reproduce the behavior

In node:

var libra = require('libra-grpc');

var client = new libra.Client('ac.testnet.libra.org:8000');

var params = {
  start_version: 1,
  limit: 10,
  fetch_events: true
};
client.request('get_transactions', params, function(err, result) {
  console.log(err, result);
});

**Comment by lorepieri8** [comment]
Solved with:

`npm install libra-grpc@0.0.7`
